### ISSUE TITLE
Where can I get the rootfs.tar.gz ?

### ISSUE THREAD

**Issue by Fanhang32** [BPI-SINOVOIP/BPI-M64-bsp#2]
![image](https://user-images.githubusercontent.com/13658277/35608448-335508ae-0694-11e8-84fa-f0ea65e9dcda.png)
As the title ,where can I get the rootfs.tar.gz ? I can't find it in the BPI-M64-BSP package . Who can help me ?

**Comment by delwinbest** [comment]
This you create yourself. I use the debootstrap method. An example can be found here :

https://community.nxp.com/docs/DOC-330147
